services:
  # Iniciar o serviço PHP com extensões necessárias
  php:
    build: .
    container_name: php_peticao
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./uploads:/var/www/html/uploads
    env_file:
      - .env
    depends_on:
      - mysql

  # Iniciar o serviço Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx_peticao
    restart: unless-stopped
    ports:
      - "8080:80" 
    volumes:
      # Mapear o diretório do código-fonte e o arquivo de configuração do Nginx
      - .:/var/www/html
      # Mapear o arquivo de configuração do Nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # Iniciar o serviço MySQL e injetar scripts de inicialização
  mysql:
    image: mysql:8.0
    container_name: mysql_peticao
    restart: unless-stopped
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # Mapear scripts de inicialização do MySQL
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
      - mysqldata:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

  phpmyadmin:
    depends_on:
      - mysql
    # use a stable tag to avoid intermittent corrupted 'latest' pulls
    image: phpmyadmin/phpmyadmin:5.2.0
    container_name: phpmyadmin_login_php
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASS}
      PMA_ABSOLUTE_URI: http://localhost:80/phpmyadmin/
      # Variables for phpMyAdmin configuration storage
      PMA_PMADB: phpmyadmin
      PMA_CONTROLUSER: pma
      PMA_CONTROLPASS: pmapass

volumes:
  mysqldata:
